# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_2' do
  pod 'Zip', '~> 1.1'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_2

  target 'test_2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
